### PR TITLE
Cleanups + support for options

### PR DESCRIPTION
**Pull request by meteficha**
This PR does some cleanups and adds support for passing options to wkhtmltopdf.

Ping @gregwebs.

### CODE REVIEW

**Comment by gregwebs** [comment]
looks good!

**Comment by alexkyllo** [comment]
Awesome, thanks for the PR @meteficha ! I will test it out and merge. I'm also thinking of adding some HUnit tests, along the lines of [wicked_pdf's test suite](https://github.com/mileszs/wicked_pdf/blob/master/test/unit/wicked_pdf_test.rb), now that the code is non-trivial.

**Comment by alexkyllo** [comment]
@meteficha what version of wkhtmltopdf did you test this with?
I have 0.9.6 (from apt-get) and I got some errors for unknown flags --collate, --background, --images, --enable-local-file-access, but it worked fine after I upgraded to the latest version 0.12.2.1. These must have been added in more recent versions, and they are all true by default in the latest version.
So, since package managers have old versions of wkhtmltopdf, then for better backward compatibility I think we should not pass those flags unless they are False. I'll add something about this to the README as well.

**Comment by meteficha** [comment]
Yes, I tested with 0.12.2.1.  How about removing these flags altogether then?

**Pull request merged**
